sudo: false
language: node_js
node_js:
  - "8"
  - "10"
  - "lts/*"
  - "node"

os:
  - linux
  - windows

addons:
  hosts:
    - nic.localhost
    - tim.localhost
    - nicola.localhost

before_install:
  - echo "No GitHub dependencies allowed" &&
    ! grep '"github:' package-lock.json

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then git config --global core.symlinks true ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cd $TRAVIS_REPO_SLUG ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then git checkout -qf $TRAVIS_COMMIT ; fi
  - npm ci

script:
  # Test the code
  - npm run standard
  - npm run nyc
  # Test global install of the package
  - npm pack .
  - npm install -g solid-server-*.tgz

after_success:
  - snyk monitor

notifications:
  email:
  - solid@janeirodigital.com
  - solid-travis@inrupt.com
